### PR TITLE
Adding Bahasa Indonesia on v6.6.x

### PR DESCRIPTION
**Pull request by sybond**
Adding Bahasa Indonesia translation.

### CODE REVIEW

**Comment by graphefruit** [comment]
Hey @sybond,
thanks for the new pull-request.
Thanks for your efforts and the translation!
I've did a short check: There are many keys not translated e.g.
`"PAGE_SETTINGS_USE_NUERMIC_KEYBOARD_FOR_GRIND_SIZE": "Numeric keyboard for grind setting?",`
Or all aroma-flavors.
Is this still in progress, or won't they be translated into Indonesia?
Thanks & Have a great cup of coffee
Lars

**Comment by sybond** [comment]
Hi, will do that. I focusing on the main menu at the moment.

What is your target for the next release?

**Comment by sybond** [comment]
Hi @graphefruit do I need to working on translation based on `develop` branch?

**Comment by graphefruit** [comment]
HI @sybond, yes develop is main.
For the next updates, we're trying to implement a tooling for translation, but I think after you're already that far, switching now is not a good idea is it?
Have a great cup of coffee
Lars

**Comment by sybond** [comment]
I don't see any big differences. Mainly just changing from `/` to `\/`. I'll work on it.

**Pull request closed without merging**
