### PR TITLE
Added confirmation when leaving Add Bean page

### PR DESCRIPTION
**Pull request by FalconPDX**
Related to [Discussion #587.](https://github.com/graphefruit/Beanconqueror/discussions/587) This change gives the user a chance to double check if they really want to leave the Add Bean page if they've made changes. This is done using a string comparison by stringifying the data after loading the page and when leaving - if there were no changes the strings should be the same, and the dialog box will consequently not be shown.

Added a new string which requires translation for the other locales.

Also fixed a small typo in the english locale.

### CODE REVIEW

**Comment by FalconPDX** [comment]
Here's a screenshot of how it looks:

**Comment by henare** [comment]
Thanks for creating this. I could have used this on the brew page this morning too 😄

**Comment by FalconPDX** [comment]
Hi Lars / @graphefruit 

I hope you don't mind me bumping this - is there anything you would like me to add/change?

**Comment by graphefruit** [comment]
Hello @FalconPDX ,
thanks for your pull-request.
I didn't have the time until now to have a deeper look.
I don't know if its just that "simple `if (JSON.stringify(this.data) !== this.initial_bean_data_stringified) {` after when I search up how to check if a JSON-Object has been changed, a realy realy more complex solution shows up.
So I need to test the implementation, in worst case a user will always have a popup when he presses back or cancel.

**Comment by graphefruit** [comment]
Hey @FalconPDX,
thanks for your support.
Somehow after I was in the process updating to Ionic 7, i used your solution and integrated already into the code (thats why no merge has happend.
I've implemented the check now for Beans aswell as for Brews, and its a Feature toggle inside the settings.
Thanks for the support
Lars

**Pull request closed without merging**
